name: daham
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  provider : ^6.1.5
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  uuid: ^4.2.1
  fl_chart: ^0.64.0
  flutter_launcher_icons: ^0.14.3
  percent_indicator: ^4.2.5
  cloud_firestore: ^5.6.7
  form_builder_validators: ^11.1.2
  flutter_localizations:
    sdk: flutter
  flutter_form_builder: ^10.0.1
  table_calendar: ^3.1.3
  fluttermoji: ^1.0.2
  awesome_dialog: ^3.2.1
  flutter_speed_dial: ^7.0.0
  flutter_dotenv: ^5.2.1
  flutter_gemini: ^3.0.0
  google_generative_ai: ^0.4.7
  grouped_list: ^6.0.0
  lottie: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lottie/
